apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: test
  labels:
    app: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: 433796583082.dkr.ecr.ap-south-1.amazonaws.com/jenkinsproject:react-92
        ports:
        - containerPort: 80
