apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-deployment
  labels:
    app: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
      - name: reactapp
        image: image:  433796583082.dkr.ecr.ap-south-1.amazonaws.com/jenkinsproject:react-87
        ports:
        - containerPort: 3000
