apiVersion: v1
kind: Service
metadata:
  name: react-app
  namespace: test
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: react-app
