apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-app
  namespace: test
  labels:
    app: tomcat-app-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat-app-1
  template:
    metadata:
      labels:
        app: tomcat-app-1
    spec:
      containers:
      - name: tomcat-app
        image: 433796583082.dkr.ecr.ap-south-1.amazonaws.com/jenkinsproject:react-98
        ports:
        - containerPort: 8080
