apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foo-app
  template:
    metadata:
      labels:
        app: foo-app
    spec:
      containers:
        - name: foo-app
          image: 433796583082.dkr.ecr.ap-south-1.amazonaws.com/jenkinsproject:reactfoo-83
          env:
            - name: APP_NAME
              value: foo
