apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  namespace: test
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: tomcat-app  
